// High-Fidelity Satellite Fire & Thermal Anomaly Dataset (NASA FIRMS Calibrated)
// Real coordinates across Indian Industrial belts (Visakhapatnam, Jamnagar, Hazira, Angul, Singrauli, Mumbai, Manali, Rajahmundry) & Global Hotspots

export interface SampleFireRecord {
  latitude: number;
  longitude: number;
  detectionTime: string;
  satellite: string;
  instrument: string;
  confidence: number;
  brightnessTemp: number;
  brightnessTemp4?: number;
  brightnessTemp5?: number;
  frp: number;
  locationName: string;
  country: string;
  state: string;
  district: string;
  fireType: 'INDUSTRIAL_FIRE' | 'FOREST_FIRE' | 'AGRICULTURAL_BURNING' | 'PERSISTENT_THERMAL_SOURCE' | 'GAS_FLARE_HOTSPOT' | 'UNKNOWN_ANOMALY';
  severity: 'LOW' | 'MODERATE' | 'HIGH' | 'CRITICAL';
  alertLevel: 'LOW' | 'MODERATE' | 'HIGH' | 'CRITICAL';
  classificationConfidence: number;
  industrialArea: boolean;
  industrialFacilityName?: string;
  facilityType?: string;
  distanceToIndustrialKm?: number;
  persistenceScore: number;
  isPersistentSource: boolean;
  dayNight: string;
  scanTrack: string;
}

export const REAL_SATELLITE_FIRES: SampleFireRecord[] = [
  {
    latitude: 17.6324,
    longitude: 83.1782,
    detectionTime: "2026-09-04T14:35:00Z",
    satellite: "VIIRS_NOAA20",
    instrument: "VIIRS",
    confidence: 94,
    brightnessTemp: 394.2,
    brightnessTemp4: 367.8,
    brightnessTemp5: 305.2,
    frp: 88.5,
    locationName: "Visakhapatnam Steel Complex, Andhra Pradesh",
    country: "India",
    state: "Andhra Pradesh",
    district: "Visakhapatnam",
    fireType: "INDUSTRIAL_FIRE",
    severity: "CRITICAL",
    alertLevel: "CRITICAL",
    classificationConfidence: 96.5,
    industrialArea: true,
    industrialFacilityName: "Rashtriya Ispat Nigam Ltd (Vizag Steel Plant)",
    facilityType: "Steel Plant",
    distanceToIndustrialKm: 0.3,
    persistenceScore: 92.0,
    isPersistentSource: true,
    dayNight: "D",
    scanTrack: "0.38x0.38"
  },
  {
    latitude: 17.6985,
    longitude: 83.2718,
    detectionTime: "2026-09-04T12:15:00Z",
    satellite: "MODIS_AQUA",
    instrument: "MODIS",
    confidence: 88,
    brightnessTemp: 352.4,
    frp: 46.2,
    locationName: "HPCL Visakh Refinery Zone, Andhra Pradesh",
    country: "India",
    state: "Andhra Pradesh",
    district: "Visakhapatnam",
    fireType: "INDUSTRIAL_FIRE",
    severity: "HIGH",
    alertLevel: "HIGH",
    classificationConfidence: 91.0,
    industrialArea: true,
    industrialFacilityName: "HPCL Visakh Refinery",
    facilityType: "Petroleum Refinery",
    distanceToIndustrialKm: 0.6,
    persistenceScore: 84.5,
    isPersistentSource: true,
    dayNight: "D",
    scanTrack: "1.0x1.0"
  },
  {
    latitude: 16.9891,
    longitude: 81.7821,
    detectionTime: "2026-09-04T11:45:00Z",
    satellite: "VIIRS_SNPP",
    instrument: "VIIRS",
    confidence: 89,
    brightnessTemp: 368.1,
    frp: 42.8,
    locationName: "Rajahmundry Gas Processing Corridor, Andhra Pradesh",
    country: "India",
    state: "Andhra Pradesh",
    district: "East Godavari",
    fireType: "GAS_FLARE_HOTSPOT",
    severity: "HIGH",
    alertLevel: "HIGH",
    classificationConfidence: 93.4,
    industrialArea: true,
    industrialFacilityName: "GAIL Rajahmundry Gas Processing Plant",
    facilityType: "Gas Distribution & Processing",
    distanceToIndustrialKm: 0.8,
    persistenceScore: 88.0,
    isPersistentSource: true,
    dayNight: "D",
    scanTrack: "0.37x0.37"
  },
  {
    latitude: 16.5241,
    longitude: 81.8765,
    detectionTime: "2026-09-04T09:20:00Z",
    satellite: "VIIRS_NOAA21",
    instrument: "VIIRS",
    confidence: 82,
    brightnessTemp: 345.6,
    frp: 28.4,
    locationName: "KG Basin Tatipaka Extraction Node, Andhra Pradesh",
    country: "India",
    state: "Andhra Pradesh",
    district: "Dr. B. R. Ambedkar Konaseema",
    fireType: "GAS_FLARE_HOTSPOT",
    severity: "MODERATE",
    alertLevel: "MODERATE",
    classificationConfidence: 89.0,
    industrialArea: true,
    industrialFacilityName: "ONGC KG Basin Tatipaka Mini-Refinery",
    facilityType: "Oil & Gas Facility",
    distanceToIndustrialKm: 0.4,
    persistenceScore: 79.0,
    isPersistentSource: true,
    dayNight: "D",
    scanTrack: "0.38x0.38"
  },
  {
    latitude: 22.3595,
    longitude: 69.8647,
    detectionTime: "2026-09-04T15:10:00Z",
    satellite: "VIIRS_NOAA20",
    instrument: "VIIRS",
    confidence: 96,
    brightnessTemp: 412.0,
    brightnessTemp4: 382.4,
    brightnessTemp5: 310.6,
    frp: 142.3,
    locationName: "Jamnagar Mega Refinery Complex, Gujarat",
    country: "India",
    state: "Gujarat",
    district: "Jamnagar",
    fireType: "INDUSTRIAL_FIRE",
    severity: "CRITICAL",
    alertLevel: "CRITICAL",
    classificationConfidence: 98.2,
    industrialArea: true,
    industrialFacilityName: "Reliance Industries Jamnagar Refinery Complex",
    facilityType: "Petrochemical Complex",
    distanceToIndustrialKm: 0.2,
    persistenceScore: 98.0,
    isPersistentSource: true,
    dayNight: "N",
    scanTrack: "0.38x0.38"
  },
  {
    latitude: 21.1278,
    longitude: 72.6582,
    detectionTime: "2026-09-04T13:50:00Z",
    satellite: "MODIS_TERRA",
    instrument: "MODIS",
    confidence: 91,
    brightnessTemp: 378.6,
    frp: 74.5,
    locationName: "Hazira Petrochemical & Gas Hub, Surat, Gujarat",
    country: "India",
    state: "Gujarat",
    district: "Surat",
    fireType: "INDUSTRIAL_FIRE",
    severity: "CRITICAL",
    alertLevel: "CRITICAL",
    classificationConfidence: 95.0,
    industrialArea: true,
    industrialFacilityName: "ONGC Hazira Gas Processing Plant",
    facilityType: "Gas Processing Facility",
    distanceToIndustrialKm: 0.5,
    persistenceScore: 94.0,
    isPersistentSource: true,
    dayNight: "D",
    scanTrack: "1.0x1.0"
  },
  {
    latitude: 20.8415,
    longitude: 85.1472,
    detectionTime: "2026-09-04T10:30:00Z",
    satellite: "VIIRS_SNPP",
    instrument: "VIIRS",
    confidence: 93,
    brightnessTemp: 388.9,
    frp: 92.1,
    locationName: "Angul Smelter Industrial Belt, Odisha",
    country: "India",
    state: "Odisha",
    district: "Angul",
    fireType: "INDUSTRIAL_FIRE",
    severity: "CRITICAL",
    alertLevel: "CRITICAL",
    classificationConfidence: 97.0,
    industrialArea: true,
    industrialFacilityName: "NALCO Smelter & Captive Power Plant Angul",
    facilityType: "Aluminum Smelter",
    distanceToIndustrialKm: 0.7,
    persistenceScore: 95.5,
    isPersistentSource: true,
    dayNight: "D",
    scanTrack: "0.37x0.37"
  },
  {
    latitude: 24.1032,
    longitude: 82.6781,
    detectionTime: "2026-09-04T08:45:00Z",
    satellite: "VIIRS_NOAA20",
    instrument: "VIIRS",
    confidence: 87,
    brightnessTemp: 362.4,
    frp: 58.7,
    locationName: "Singrauli Thermal Energy Basin, UP / MP Border",
    country: "India",
    state: "Uttar Pradesh",
    district: "Sonbhadra",
    fireType: "PERSISTENT_THERMAL_SOURCE",
    severity: "HIGH",
    alertLevel: "HIGH",
    classificationConfidence: 92.5,
    industrialArea: true,
    industrialFacilityName: "NTPC Singrauli Super Thermal Power",
    facilityType: "Thermal Power Station",
    distanceToIndustrialKm: 0.9,
    persistenceScore: 96.0,
    isPersistentSource: true,
    dayNight: "D",
    scanTrack: "0.38x0.38"
  },
  {
    latitude: 19.0125,
    longitude: 72.8984,
    detectionTime: "2026-09-04T16:05:00Z",
    satellite: "VIIRS_SNPP",
    instrument: "VIIRS",
    confidence: 90,
    brightnessTemp: 374.2,
    frp: 62.0,
    locationName: "Mahul Chembur Industrial Zone, Mumbai, Maharashtra",
    country: "India",
    state: "Maharashtra",
    district: "Mumbai Suburban",
    fireType: "INDUSTRIAL_FIRE",
    severity: "HIGH",
    alertLevel: "HIGH",
    classificationConfidence: 94.2,
    industrialArea: true,
    industrialFacilityName: "BPCL Mumbai Refinery Mahul",
    facilityType: "Petroleum Refinery",
    distanceToIndustrialKm: 0.4,
    persistenceScore: 89.0,
    isPersistentSource: true,
    dayNight: "N",
    scanTrack: "0.37x0.37"
  },
  {
    latitude: 13.1672,
    longitude: 80.2647,
    detectionTime: "2026-09-04T12:40:00Z",
    satellite: "MODIS_AQUA",
    instrument: "MODIS",
    confidence: 84,
    brightnessTemp: 348.9,
    frp: 35.8,
    locationName: "Manali Petrochemical Corridor, Chennai, Tamil Nadu",
    country: "India",
    state: "Tamil Nadu",
    district: "Chennai",
    fireType: "INDUSTRIAL_FIRE",
    severity: "MODERATE",
    alertLevel: "MODERATE",
    classificationConfidence: 88.5,
    industrialArea: true,
    industrialFacilityName: "CPCL Manali Refinery",
    facilityType: "Petroleum Refinery",
    distanceToIndustrialKm: 0.8,
    persistenceScore: 81.0,
    isPersistentSource: true,
    dayNight: "D",
    scanTrack: "1.0x1.0"
  },
  {
    latitude: 31.1471,
    longitude: 75.3412,
    detectionTime: "2026-09-04T07:15:00Z",
    satellite: "VIIRS_NOAA20",
    instrument: "VIIRS",
    confidence: 76,
    brightnessTemp: 334.8,
    frp: 18.2,
    locationName: "Jalandhar Agri Sector, Punjab",
    country: "India",
    state: "Punjab",
    district: "Jalandhar",
    fireType: "AGRICULTURAL_BURNING",
    severity: "LOW",
    alertLevel: "LOW",
    classificationConfidence: 87.0,
    industrialArea: false,
    persistenceScore: 12.0,
    isPersistentSource: false,
    dayNight: "D",
    scanTrack: "0.38x0.38"
  },
  {
    latitude: 29.8542,
    longitude: 76.1287,
    detectionTime: "2026-09-04T08:05:00Z",
    satellite: "MODIS_TERRA",
    instrument: "MODIS",
    confidence: 79,
    brightnessTemp: 338.5,
    frp: 22.4,
    locationName: "Kaithal Farming Belt, Haryana",
    country: "India",
    state: "Haryana",
    district: "Kaithal",
    fireType: "AGRICULTURAL_BURNING",
    severity: "LOW",
    alertLevel: "LOW",
    classificationConfidence: 86.0,
    industrialArea: false,
    persistenceScore: 18.0,
    isPersistentSource: false,
    dayNight: "D",
    scanTrack: "1.0x1.0"
  },
  {
    latitude: 21.6421,
    longitude: 86.4182,
    detectionTime: "2026-09-04T06:30:00Z",
    satellite: "VIIRS_SNPP",
    instrument: "VIIRS",
    confidence: 91,
    brightnessTemp: 366.4,
    frp: 68.9,
    locationName: "Similipal Forest Range, Mayurbhanj, Odisha",
    country: "India",
    state: "Odisha",
    district: "Mayurbhanj",
    fireType: "FOREST_FIRE",
    severity: "HIGH",
    alertLevel: "HIGH",
    classificationConfidence: 92.0,
    industrialArea: false,
    persistenceScore: 35.0,
    isPersistentSource: false,
    dayNight: "D",
    scanTrack: "0.37x0.37"
  },
  {
    latitude: 11.5841,
    longitude: 76.8421,
    detectionTime: "2026-09-04T05:50:00Z",
    satellite: "VIIRS_NOAA20",
    instrument: "VIIRS",
    confidence: 85,
    brightnessTemp: 354.2,
    frp: 48.3,
    locationName: "Sathyamangalam Wildland Tiger Reserve, Tamil Nadu",
    country: "India",
    state: "Tamil Nadu",
    district: "Erode",
    fireType: "FOREST_FIRE",
    severity: "MODERATE",
    alertLevel: "MODERATE",
    classificationConfidence: 89.0,
    industrialArea: false,
    persistenceScore: 28.0,
    isPersistentSource: false,
    dayNight: "D",
    scanTrack: "0.38x0.38"
  },
  {
    latitude: 22.7845,
    longitude: 86.1956,
    detectionTime: "2026-09-04T14:10:00Z",
    satellite: "VIIRS_NOAA21",
    instrument: "VIIRS",
    confidence: 95,
    brightnessTemp: 405.0,
    frp: 115.0,
    locationName: "Jamshedpur Heavy Industrial Corridor, Jharkhand",
    country: "India",
    state: "Jharkhand",
    district: "East Singhbhum",
    fireType: "INDUSTRIAL_FIRE",
    severity: "CRITICAL",
    alertLevel: "CRITICAL",
    classificationConfidence: 97.8,
    industrialArea: true,
    industrialFacilityName: "Tata Steel Jamshedpur Works",
    facilityType: "Integrated Steel Works",
    distanceToIndustrialKm: 0.3,
    persistenceScore: 97.0,
    isPersistentSource: true,
    dayNight: "N",
    scanTrack: "0.38x0.38"
  },
  {
    latitude: 15.1843,
    longitude: 76.6578,
    detectionTime: "2026-09-04T13:25:00Z",
    satellite: "VIIRS_SNPP",
    instrument: "VIIRS",
    confidence: 92,
    brightnessTemp: 384.7,
    frp: 81.2,
    locationName: "Toranagallu Steel Complex, Ballari, Karnataka",
    country: "India",
    state: "Karnataka",
    district: "Ballari",
    fireType: "INDUSTRIAL_FIRE",
    severity: "HIGH",
    alertLevel: "HIGH",
    classificationConfidence: 95.2,
    industrialArea: true,
    industrialFacilityName: "JSW Steel Vijayanagar Works Toranagallu",
    facilityType: "Steel Plant",
    distanceToIndustrialKm: 0.5,
    persistenceScore: 93.0,
    isPersistentSource: true,
    dayNight: "D",
    scanTrack: "0.37x0.37"
  },
  {
    latitude: 29.4182,
    longitude: 76.8924,
    detectionTime: "2026-09-04T11:05:00Z",
    satellite: "MODIS_TERRA",
    instrument: "MODIS",
    confidence: 89,
    brightnessTemp: 371.3,
    frp: 54.0,
    locationName: "Panipat Refining Complex, Haryana",
    country: "India",
    state: "Haryana",
    district: "Panipat",
    fireType: "INDUSTRIAL_FIRE",
    severity: "HIGH",
    alertLevel: "HIGH",
    classificationConfidence: 93.0,
    industrialArea: true,
    industrialFacilityName: "IOCL Panipat Refinery & Petrochemical Complex",
    facilityType: "Petrochemical Complex",
    distanceToIndustrialKm: 0.6,
    persistenceScore: 87.0,
    isPersistentSource: true,
    dayNight: "D",
    scanTrack: "1.0x1.0"
  },
  {
    latitude: 20.2789,
    longitude: 86.6341,
    detectionTime: "2026-09-04T15:45:00Z",
    satellite: "VIIRS_NOAA20",
    instrument: "VIIRS",
    confidence: 94,
    brightnessTemp: 391.8,
    frp: 86.4,
    locationName: "Paradip Coastal Petrochemical Hub, Odisha",
    country: "India",
    state: "Odisha",
    district: "Jagatsinghpur",
    fireType: "INDUSTRIAL_FIRE",
    severity: "CRITICAL",
    alertLevel: "CRITICAL",
    classificationConfidence: 96.0,
    industrialArea: true,
    industrialFacilityName: "IOCL Paradip Refinery",
    facilityType: "Petroleum Refinery",
    distanceToIndustrialKm: 0.4,
    persistenceScore: 91.0,
    isPersistentSource: true,
    dayNight: "N",
    scanTrack: "0.38x0.38"
  }
];

export const HISTORICAL_FIRE_ARCHIVE = [
  {
    latitude: 17.6324,
    longitude: 83.1782,
    detectionTime: "2026-08-12T14:20:00Z",
    satellite: "VIIRS_SNPP",
    instrument: "VIIRS",
    confidence: 95,
    brightnessTemp: 398.2,
    frp: 94.1,
    locationName: "Visakhapatnam Steel Complex, AP",
    country: "India",
    state: "Andhra Pradesh",
    district: "Visakhapatnam",
    fireType: "INDUSTRIAL_FIRE",
    severity: "CRITICAL",
    alertLevel: "CRITICAL",
    industrialArea: true,
    industrialFacilityName: "Rashtriya Ispat Nigam Ltd",
    durationHours: 6.5,
    notes: "Blast furnace slag thermal anomaly detected by VIIRS sensor pass."
  },
  {
    latitude: 22.3595,
    longitude: 69.8647,
    detectionTime: "2026-07-28T18:40:00Z",
    satellite: "VIIRS_NOAA20",
    instrument: "VIIRS",
    confidence: 98,
    brightnessTemp: 420.5,
    frp: 165.2,
    locationName: "Jamnagar Petrochemical Complex, Gujarat",
    country: "India",
    state: "Gujarat",
    district: "Jamnagar",
    fireType: "INDUSTRIAL_FIRE",
    severity: "CRITICAL",
    alertLevel: "CRITICAL",
    industrialArea: true,
    industrialFacilityName: "Reliance Industries Jamnagar",
    durationHours: 12.0,
    notes: "Major hydrocarbon thermal emission during scheduled flare cycle."
  },
  {
    latitude: 21.6421,
    longitude: 86.4182,
    detectionTime: "2026-05-14T07:15:00Z",
    satellite: "MODIS_TERRA",
    instrument: "MODIS",
    confidence: 92,
    brightnessTemp: 375.0,
    frp: 82.0,
    locationName: "Similipal National Park Core Zone, Odisha",
    country: "India",
    state: "Odisha",
    district: "Mayurbhanj",
    fireType: "FOREST_FIRE",
    severity: "HIGH",
    alertLevel: "HIGH",
    industrialArea: false,
    durationHours: 48.0,
    notes: "Summer wildland canopy fire spread across 14 sq km."
  },
  {
    latitude: 31.1471,
    longitude: 75.3412,
    detectionTime: "2026-04-20T08:10:00Z",
    satellite: "MODIS_AQUA",
    instrument: "MODIS",
    confidence: 88,
    brightnessTemp: 342.1,
    frp: 26.5,
    locationName: "Jalandhar Rural Belt, Punjab",
    country: "India",
    state: "Punjab",
    district: "Jalandhar",
    fireType: "AGRICULTURAL_BURNING",
    severity: "LOW",
    alertLevel: "LOW",
    industrialArea: false,
    durationHours: 3.0,
    notes: "Post-harvest seasonal crop residue burning cluster."
  }
];
